# Generated by Django 4.2.6 on 2023-10-24 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroommembership',
            old_name='user',
            new_name='username',
        ),
    ]
