# Generated by Django 4.2.6 on 2023-10-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_user_chatroommembership_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroommembership',
            name='chat_room',
            field=models.CharField(max_length=100),
        ),
    ]
